package co.unicauca.onlinerestaurant.client.presentation;

import static java.awt.Frame.MAXIMIZED_BOTH;
import java.beans.PropertyVetoException;

/**
 * Crea un jInternalFrame para el CRUD de platos principales
 *
 * @author Santiago Acuña
 */
public class GUIMenuFoodDishes extends javax.swing.JInternalFrame {

    /**
     * Guarda la instancia del formulario crear plato
     */
    private final GUICreateDishe CreateDishe = new GUICreateDishe();
    /**
     * Guarda la instancia del formulario buscar plato
     */
    private final GUIFindDishe FindDishe = new GUIFindDishe();
    /**
     * Guarda la instancia del formulario modificar plato
     */
    private final GUIModifyDishe ModifyDishe = new GUIModifyDishe();
    /**
     * Guarda la instancia del formulario borrar plato
     */
    private final GUIDeleteDishe DeleteDishe = new GUIDeleteDishe();

    /**
     * Constructor para inicializar componentes
     *
     * @throws PropertyVetoException
     */
    public GUIMenuFoodDishes() throws PropertyVetoException {
        initComponents();
        this.setMaximum(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dskEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemCreateDishe = new javax.swing.JMenuItem();
        jMenuItemFindDishe = new javax.swing.JMenuItem();
        jMenuItemModifyDishe = new javax.swing.JMenuItem();
        jMenuItemDeleteDishe = new javax.swing.JMenuItem();

        setClosable(true);
        setResizable(true);

        javax.swing.GroupLayout dskEscritorioLayout = new javax.swing.GroupLayout(dskEscritorio);
        dskEscritorio.setLayout(dskEscritorioLayout);
        dskEscritorioLayout.setHorizontalGroup(
            dskEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 535, Short.MAX_VALUE)
        );
        dskEscritorioLayout.setVerticalGroup(
            dskEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );

        getContentPane().add(dskEscritorio, java.awt.BorderLayout.CENTER);

        jMenuBar1.setBackground(new java.awt.Color(54, 33, 88));

        jMenu1.setBackground(new java.awt.Color(54, 33, 88));
        jMenu1.setForeground(new java.awt.Color(204, 204, 204));
        jMenu1.setText("Dishes");

        jMenuItemCreateDishe.setBackground(new java.awt.Color(54, 33, 88));
        jMenuItemCreateDishe.setForeground(new java.awt.Color(204, 204, 204));
        jMenuItemCreateDishe.setText("Create Dish");
        jMenuItemCreateDishe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCreateDisheActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemCreateDishe);

        jMenuItemFindDishe.setBackground(new java.awt.Color(54, 33, 88));
        jMenuItemFindDishe.setForeground(new java.awt.Color(204, 204, 204));
        jMenuItemFindDishe.setText("Find Dish");
        jMenuItemFindDishe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFindDisheActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemFindDishe);

        jMenuItemModifyDishe.setBackground(new java.awt.Color(54, 33, 88));
        jMenuItemModifyDishe.setForeground(new java.awt.Color(204, 204, 204));
        jMenuItemModifyDishe.setText("Modify Dish");
        jMenuItemModifyDishe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemModifyDisheActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemModifyDishe);

        jMenuItemDeleteDishe.setBackground(new java.awt.Color(54, 33, 88));
        jMenuItemDeleteDishe.setForeground(new java.awt.Color(204, 204, 204));
        jMenuItemDeleteDishe.setText("Delete Dishe");
        jMenuItemDeleteDishe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDeleteDisheActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemDeleteDishe);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Inicializa el formulario crear plato
     *
     * @param evt evento del menu item
     */
    private void jMenuItemCreateDisheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCreateDisheActionPerformed

        if (!CreateDishe.isVisible()) {
            CreateDishe.setMaximizable(true);
            dskEscritorio.add(CreateDishe);
            CreateDishe.show();
        }

    }//GEN-LAST:event_jMenuItemCreateDisheActionPerformed

    /**
     * Inicializar el formulario buscar plato
     *
     * @param evt evento del menu item
     */
    private void jMenuItemFindDisheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFindDisheActionPerformed
        if (!FindDishe.isVisible()) {
            FindDishe.setMaximizable(true);
            dskEscritorio.add(FindDishe);
            FindDishe.show();
        }

    }//GEN-LAST:event_jMenuItemFindDisheActionPerformed

    /**
     * Inicializa el formulario modificar plato
     *
     * @param evt evento del menu item
     */
    private void jMenuItemModifyDisheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemModifyDisheActionPerformed
        if (!ModifyDishe.isVisible()) {
            ModifyDishe.setMaximizable(true);
            dskEscritorio.add(ModifyDishe);
            ModifyDishe.show();
        }

    }//GEN-LAST:event_jMenuItemModifyDisheActionPerformed

    /**
     * Inicializa el formulario borrar plato
     *
     * @param evt evento del meun item
     */
    private void jMenuItemDeleteDisheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDeleteDisheActionPerformed
        if (!DeleteDishe.isVisible()) {
            DeleteDishe.setMaximizable(true);
            dskEscritorio.add(DeleteDishe);
            DeleteDishe.show();
        }

    }//GEN-LAST:event_jMenuItemDeleteDisheActionPerformed

    /**
     * Metodo encargado de inicializar el formulario de menu para platos de
     * comida
     *
     * @param args
     * @throws PropertyVetoException
     */
    public static void main(String[] args) throws PropertyVetoException {
        GUIMenuFoodDishes gui = new GUIMenuFoodDishes();
        gui.setVisible(true);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dskEscritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemCreateDishe;
    private javax.swing.JMenuItem jMenuItemDeleteDishe;
    private javax.swing.JMenuItem jMenuItemFindDishe;
    private javax.swing.JMenuItem jMenuItemModifyDishe;
    // End of variables declaration//GEN-END:variables
}
